#ifndef ASTNODETYPE
# define ASTNODETYPE
enum ASTNODETYPE {
    ASTNODE,
    ASSIGNNODE,
    BITWISENODE,
    DECLNODE,
    FORNODE,
    IFNODE,
    LOGICALNODE,
    NONENODE,
    RELATIONALNODE,
    RETURNNODE,
    SEQNODE,
    TYPENODE,
    ARRAYNODE,
    BINARYMATHNODE,
    CASTNODE,
    CHARNODE,
    FLOATNODE,
    FUNCNODE,
    IDENTIFIERNODE,
    INTNODE,
    STRINGNODE,
    UNARYNODE,
    WHILENODE
};
#endif